[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/manifest.webmanifest"
  to = "/manifest.webmanifest"
  status = 200

[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200

# Fallback to SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
