// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

//myOrg
const SUPABASE_URL = "https://vqieauvmkrcgyoxulndg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxaWVhdXZta3JjZ3lveHVsbmRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2NzM1MTUsImV4cCI6MjA1MjI0OTUxNX0.jK3BxJtQ_TGdjozaSdkTjMNwsBmn_3s-QI6mBdqPwpo";

//nice2 details
// const SUPABASE_URL = "https://vqieauvmkrcgyoxulndg.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxaWVhdXZta3JjZ3lveHVsbmRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2NzM1MTUsImV4cCI6MjA1MjI0OTUxNX0.jK3BxJtQ_TGdjozaSdkTjMNwsBmn_3s-QI6mBdqPwpo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);